trigger:
  - main

pool:
  vmImage: 'macOS-latest'

jobs:
  - job: Build
    displayName: 'Build job'
    steps:
      - script: |
          echo "JDK File Path: $(Agent.BuildDirectory)/openjdk-11.0.2_osx-x64_bin.tar.gz"
      - task: Gradle@2
        displayName: 'Building Project'
        continueOnError: false
        inputs:
          versionSpec: '8'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          tasks: 'assembleDebug'
          codeCoverageToolOption: 'None'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: 'default'
          checkStyleRunAnalysis: false
          findBugsRunAnalysis: false
