
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      architecture: 'x64'

  - script: |
      wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk-tools.zip
      unzip -q android-sdk-tools.zip -d $HOME/android-sdk
      export ANDROID_HOME=$HOME/android-sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      echo 'ANDROID_HOME: ' $ANDROID_HOME
      echo 'PATH: ' $PATH
      ls -la $ANDROID_HOME/cmdline-tools/latest/bin
      ls -la $ANDROID_HOME/platform-tools
      source $HOME/.bashrc
      yes | sdkmanager --licenses
      sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
    displayName: 'Install Android SDK'

  - task: Gradle@2
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/path/to/your/android/app'
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build connectedAndroidTest'
      options: '-Xmx3072m'