# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - master

pool:
  vmImage: 'macOS-latest'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      arch: 'x64'
      addToPath: true

  - script: |
      echo 'y' | sdkmanager --licenses
    displayName: 'Accept Android SDK Licenses'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'assembleDebug'
      options: '-Xmx3072m'

