# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
  - master

pool:
  vmImage: 'macOS-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'path'
      jdkPath: '/Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home'

  - script: |
      echo 'y' | sdkmanager --licenses
    displayName: 'Accept Android SDK Licenses'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'assembleDebug'
      options: '-Xmx3072m'



