trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
  - script: |
      echo 'Files List'
      ls $(System.DefaultWorkingDirectory)
    displayName: 'List Files in Present Working Directory'

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
      unzip commandlinetools-linux-6609375_latest.zip -d cmdline-tools
      mkdir --parents "$ANDROID_HOME/cmdline-tools/latest"
      sudo mv cmdline-tools/* "$ANDROID_HOME/cmdline-tools/latest/"
      export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
    displayName: 'Install Android SDK'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'assembleDebug'
      options: '-Xmx3072m'
